# Generated by Django 2.0.2 on 2018-04-04 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ZooMaps', 'initial_populate_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userbis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
