# Generated by Django 2.0.2 on 2018-04-04 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0001_user_userbis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your username', max_length=20)),
                ('password', models.CharField(default='', help_text='Enter your password', max_length=20)),
                ('emailAddress', models.CharField(default='', help_text='Enter your email address', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userbis',
        ),
        migrations.AlterField(
            model_name='commentevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(help_text='Users going to your Event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
