# Generated by Django 2.0.2 on 2018-04-04 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0002_auto_20180403_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='latitue',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='commentevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
