# Generated by Django 2.0.2 on 2018-04-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0003_auto_20180403_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageevent',
            name='object',
        ),
    ]
