# Generated by Django 2.0.2 on 2018-04-04 02:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ZooMaps', '0004_remove_messageevent_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentEvent',
            new_name='RatingEvent',
        ),
    ]
