#!/usr/bin/env python3
import os, sys, subprocess, argparse
from django.core.wsgi import get_wsgi_application
from django.core.management import call_command

"""
Master script that takes optional arguments and runs the correspoding script.
The script's purpose is to perform common tasks such as running the server,
making migrations, running tests, etc. Runs the server by default if no argument
is provided.
"""

def print_cmd(cmd):
    """
    Method to print the shell command and arguments to stdout.

    Args:
        cmd (str): String representing command to be run
    Returns:
        None

    """
    print('Running: {0}\n'.format(' '.join(a for a in [cmd])))
    sys.stdout.flush()  # Make sure stdout is flushed before continuing.


if __name__ == '__main__':
    proj_path = os.getcwd()
    # This is so Django knows where to find stuff.
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "GTech.settings")
    sys.path.append(proj_path)

    # This is so my local_settings.py gets loaded.
    os.chdir(proj_path)

    # This is so models get loaded.
    application = get_wsgi_application()

    # Get the given command line argument, if there is one, representing the actions to perform.
    args = sys.argv[1:]
    cmd = None
    if args:
        cmd = args[0]

    # Run server if no argument provided
    if not cmd or cmd == 'server':
        # TODO check if migrations need to be performed, if they do, prompt user to perform them.
        call_command('runserver',  '127.0.0.1:8000')
    elif cmd == 'build':
        print('Creating/updating database...')
        print_cmd('python manage.py makemigrations ZooMaps')
        call_command('makemigrations', 'ZooMaps')
        print_cmd('python manage.py migrate')
        call_command('migrate')

        # TODO: Make calls to loaddata to load any fixtures (including the superuser)
    elif cmd == 'test':
        print('Running test suite in tests directory')
        pass
    elif cmd == 'dev':
    # TODO (OPTIONAL): Run a linter over our code
        pass
    elif cmd == 'clean':
    # TODO (OPTIONAL): Clean extraneous files like '__init__.py' files, pycache directories, migrations files generated by Django, etc.
        print('You are about to delete migrations files. Would you like to proceed (y/n)?')
        pass
    sys.exit()
