# Generated by Django 2.0.2 on 2018-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Event', max_length=20)),
                ('description', models.TextField(help_text='Enter a brief description of the Event', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(help_text='Enter a tag', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your username', max_length=20)),
                ('password', models.CharField(default='', help_text='Enter your password', max_length=20)),
                ('emailAddress', models.CharField(default='', help_text='Enter your email address', max_length=20)),
                ('futureEvents', models.ManyToManyField(default='', help_text='Select your favorite events', to='ZooMaps.Event')),
            ],
        ),
    ]
