# Generated by Django 2.0.2 on 2018-03-29 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Event', max_length=20)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(help_text='Enter a brief description of the Event', max_length=1000)),
                ('emoji', models.CharField(help_text='Enter the emojis of the Event', max_length=20)),
                ('latitue', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(help_text='Enter the object of your message', max_length=20)),
                ('comment', models.TextField(help_text='Enter a brief message for the otehr users interested in the event', max_length=1000)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(help_text='Enter a tag', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your username', max_length=20)),
                ('password', models.CharField(default='', help_text='Enter your password', max_length=20)),
                ('emailAddress', models.CharField(default='', help_text='Enter your email address', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='messageevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(help_text='Users going to your Event', to='ZooMaps.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text='Select your favorite tags for the Event', to='ZooMaps.Tag'),
        ),
        migrations.AddField(
            model_name='commentevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.Event'),
        ),
        migrations.AddField(
            model_name='commentevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.User'),
        ),
    ]
