# Generated by Django 2.0.2 on 2018-03-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
