# Generated by Django 2.0.2 on 2018-03-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0002_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='pr', max_length=2),
        ),
    ]
