# Generated by Django 2.0.2 on 2018-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0002_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(help_text='Enter a tag', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(default='', help_text='Enter the name of the Event', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(blank=True, default='2018-06-16', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='latitue',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='pr', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(default='', help_text='Select your favorite tags for this event', to='ZooMaps.Tag'),
        ),
    ]
