# Generated by Django 2.0.2 on 2018-03-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0003_auto_20180307_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Enter the name of the Event', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Enter the name of the Place', max_length=20),
        ),
    ]
