# Generated by Django 2.0.2 on 2018-03-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0004_auto_20180307_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='-', help_text='Enter the address of the Place', max_length=40),
        ),
    ]
