# Generated by Django 2.0.2 on 2018-03-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0005_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='-', help_text='Enter a brief description of the Event', max_length=1000),
        ),
    ]
