# Generated by Django 2.0.2 on 2018-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0005_auto_20180309_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emoji',
            field=models.CharField(help_text='Enter the name of the Event', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text='Select your favorite tags for this event', to='ZooMaps.Tag'),
        ),
    ]
