# Generated by Django 2.0.2 on 2018-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0006_auto_20180309_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emoji',
            field=models.CharField(help_text='Enter the emojis of the Event', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text='Select your favorite tags for the Event', to='ZooMaps.Tag'),
        ),
    ]
