# Generated by Django 2.0.2 on 2018-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0007_auto_20180307_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Enter the address of the Place', max_length=40),
        ),
    ]
