# Generated by Django 2.0.2 on 2018-03-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0008_commentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('object', models.CharField(help_text='Enter the object of your message', max_length=20)),
                ('message', models.TextField(help_text='Enter a brief comment for the event', max_length=1000)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.Event')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.User')),
            ],
        ),
    ]
