# Generated by Django 2.0.3 on 2018-03-20 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0009_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='event',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.RemoveField(
            model_name='event',
            name='private',
        ),
        migrations.RemoveField(
            model_name='user',
            name='futureEvents',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(help_text='Users going to your Event', to='ZooMaps.User'),
        ),
        migrations.AlterField(
            model_name='commentevent',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
