# Generated by Django 2.0.2 on 2018-03-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0010_auto_20180320_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter a brief message for the otehr users interested in the event', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentevent',
            name='comment',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Users going to your Event', null=True, to='ZooMaps.User'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.Event'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZooMaps.User'),
        ),
    ]
