# Generated by Django 2.0.2 on 2018-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooMaps', '0011_auto_20180324_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageevent',
            name='object',
            field=models.CharField(default='aa', help_text='Enter the object of your message', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(help_text='Users going to your Event', to='ZooMaps.User'),
        ),
    ]
