# Generated by Django 2.0.2 on 2018-03-27 21:09

from django.db import migrations

def make_users(apps, schema_editor):
  '''
  Creates a set of initial users for the database
  '''

  User = apps.get_model('ZooMaps', 'User')
  email_domains = ['umass.edu']

  for i in range(1, 26):
    username = '{:0>3}'.format(i)
    password = username
    domain = email_domains[0]
    email_address = f'{username}@{domain}'
    User.objects.get_or_create(username=username, password=password, emailAddress=email_address)


class Migration(migrations.Migration):

    dependencies = [
      ('ZooMaps', '0001_initial')
    ]

    operations = [
        migrations.RunPython(make_users)
    ]
